### ISSUE TITLE
undefined local variable or method `attachment' ComfortableMexicanSofa::Content::Tag::File-Object

### ISSUE THREAD

**Issue by vs-de** [comfy/comfortable-mexican-sofa#853] opened 2018-11-13 15:04 UTC
Hi. First of all: thanks for this great engine!
Everything else worked great from the beginning, so i'm not perfectly sure if i just missed something in the docs. Sorry if this is the case. The issue:

### Expected behavior
When i create a layout and add the line (like in the your wiki-docs)
`{{ cms:file example, as: image, label: "My Photo", resize: "100x50>", gravity: "center", crop: "100x50+0+0"}}`
then i get an upload-field in the page-view for this file and when i upload a file it should be processed by image-magick and shown on the corresponding page.
If this doesn't work for any reason, the reason should be displayed somehow somewhere (image_magick gem needed or something like this)
### Actual behavior
The upload works, but when i visit the site i get the following error (when i omit the mogrify-instructions there is no error):
```
NameError (undefined local variable or method `attachment' for #<ComfortableMexicanSofa::Content::Tag::File:0x00007f5de43e1310>):
  
comfortable_mexican_sofa (2.0.17) lib/comfortable_mexican_sofa/content/tags/mixins/file_content.rb:15:in `content'
comfortable_mexican_sofa (2.0.17) lib/comfortable_mexican_sofa/content/tags/fragment.rb:47:in `render'
comfortable_mexican_sofa (2.0.17) lib/comfortable_mexican_sofa/content/renderer.rb:62:in `block in render'
comfortable_mexican_sofa (2.0.17) lib/comfortable_mexican_sofa/content/renderer.rb:57:in `map'
comfortable_mexican_sofa (2.0.17) lib/comfortable_mexican_sofa/content/renderer.rb:57:in `render'
comfortable_mexican_sofa (2.0.17) app/models/concerns/comfy/cms/with_fragments.rb:89:in `render'
comfortable_mexican_sofa (2.0.17) app/controllers/comfy/admin/cms/pages_controller.rb:148:in `preview_page'
activesupport (5.2.1) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.1) lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (5.2.1) lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
activesupport (5.2.1) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (5.2.1) lib/active_support/callbacks.rb:513:in `each'
activesupport (5.2.1) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (5.2.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

### System configuration
**Rails version**: 5.2.1

**CMS version**: 2.0.17

**Ruby version**: 2.5.1

Thanks for any advise or hint on this

**Comment by GBH** [comment] 2018-11-25 20:46
I can't replicate issue you're encountering. Can you `bundle open comfortable_mexican_sofa` and so some debugging there? I can't understand why there's `tag.attachment` call happening.

**Comment by vs-de** [comment] 2018-11-26 11:21
OK, that's a bit weird from the beginning: even when i test for this by using respond_to? this happens but i'll update you on this very soon...
![2018-11-26-121455_1168x318_scrot](https://user-images.githubusercontent.com/219852/49011033-4c65ae80-f175-11e8-9e86-c0281c5558da.png)

**Comment by jaybloke** [comment] 2018-12-03 06:55
I'm experiencing the exact same problem. Using identical versions to @vs-de .

**Comment by vs-de** [comment] 2018-12-13 16:33
Just to be sure, here are the steps to reproduce:
 echo 2.5.1 > .ruby-version
( ruby -v should give sth like
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux])
rails new sofa
cd sofa
add comfy to Gemfile
bundle
rails g comfy:cms
rails active_storage:install
rails db:migrate
rails s
then just add a layout and a page as described.

**Comment by vs-de** [comment] 2019-01-02 13:12
What does this mean exactly? Shouldn't it work with the default :local setting?
My config/storage.yml is present and the local entry is the default entry and ActiveStorage is working.
![2019-01-02-141048_965x139_scrot](https://user-images.githubusercontent.com/219852/50593335-452e7080-0e98-11e9-81b5-88537eb4e980.png)
image shows that ActiveStorage has attachment-records present and it's finding them without problems

**Comment by jh2633** [comment] 2019-02-20 14:53
The cause of this issue was actually addressed in this commit; however this PR came after version 2.0.0 of the Gem. Pulling the latest version of CMS should resolve the issue 
https://github.com/comfy/comfortable-mexican-sofa/commit/5846c148a64b5d3de4b8a090d051aa70ec0fb887

**Comment by vs-de** [comment] 2019-02-21 22:37
You are right. Thank you very much for the hint. Maybe one of the following commits should be tagged with 2.0.18 ? I'm closing the issue now.

**Closed** 2019-02-21 22:37 UTC
Labels: bug

**Comment by GBH** [comment] 2019-02-21 23:04
Thanks for figuring this out. No wonder I could not replicate. Will prepare release that includes this fix.

**Comment by collinsbrian** [comment] 2019-03-05 00:50
Is there a GEM release that contains commit 5846c14? Experiencing same error. I think i need a public GEM to have issue fixed in Heroku Dyno
