### ISSUE TITLE
Devise integration with role authorisation

### ISSUE THREAD

**Issue by danielmyasnikov** [comfy/comfortable-mexican-sofa#606] opened 2015-02-18 10:19 UTC
That would be great to have devise and cancan (cancancan) setup for multiple admin roles, with ability for super admin to edit roles on the backend.

Please let me know if that feature is coming, otherwise I'd like to make a push request.

**Comment by GBH** [comment] 2015-02-18 19:17
Sofa will not have user and authorization system baked in. However it allows to inject that fairly easily. 
Authorization is possible after [1.12.3](https://github.com/comfy/comfortable-mexican-sofa/releases/tag/v1.12.3)

Alternatively there's https://github.com/melvinsembrano/cms-fortress that adds a lot of functionality, authentication/authorization as well.

**Comment by andywenk** [comment] 2015-03-04 12:40
@GBH may I ask why "Sofa will not have user and authorization system baked in". Imho there is no need to have both comfy and cms-fortress as seperate projects.

**Comment by GBH** [comment] 2015-03-05 03:04
Well, it's just that I don't want to make decisions about that auth system you going to have in your app. Sofa is a plugin, and should be able to work with whatever you already may have. If I implement Devise/CanCanCan somebody might spend a lot of time trying to get rid of it because they want Sorcery/Pundit. Also this minimizes 3rd party dependencies. This is why I can spend a day or two and get CMS working with newest Rails.

Less features == Better

**Comment by andywenk** [comment] 2015-03-05 08:15
Thank you @GBH. What you say is true on one hand. On the other hand I think that a CMS does always need authentication. And out of this assumption I assume furthermore that most of the people do need authentication. I have never seen a CMS without that. 

Minimizing third party dependencies is not a problem imho. Bundler is perfect for solving dependency issues. 

I don't quite understand Less features == Better. For sure, one thing should do exactly the defined job. And Comfy is doing this very well! But in my world, the definition of a CMS is including authentication, authorisation and roles.

Disclaimer: my position may sound biased. And yes we are using cms-fortress. So this position may not reflect the one from @GBH and others. Please take this as a base for a discussion about why we need comfy and also cms-fortress.

**Comment by nasmorn** [comment] 2015-03-05 11:26
There is an important use case of comfy where you take any old application and slap a CMS on it. This application can already have tons of stuff going on. Comfy is uniquely suited for this because it does not make tons of assumptions for you. Compare this with Locomotive where you can only run it out of MongoDB making an integration very unwieldy.

That said, I think there could be a way to set this up for new projects. But maybe cmd-fortress is that project already. I haven't looked at it too closely yet.

**Comment by andywenk** [comment] 2015-03-05 11:34
ADDING INFO: one problem I see is that cms-fortress "must" monkey patch a lot of the comfy code

@nasmorn Thanks a lot for your input. Yes I understand that you simply want to have a plugin you put onto an existing application. But when you decide to do this, in my experience at least, you would better throw away that application and rewrite it from scratch (this is btw. an approved fact - https://vimeo.com/9270320). 

I still think that a minimum requirement for a CMS is authentication and so on.

**Comment by wyaeld** [comment] 2015-03-29 03:38
I'm actually very grateful to @GBH for leaving the decision open, much like Rails does.

The issue isn't that Authentication & Authorization aren't key concerns for most webapps, they are.  But the requirements for the developers vary so widely, that baking 1 choice into the core framework makes it so much harder for everyone who needs something to work a little differently.

**Comment by andywenk** [comment] 2015-03-30 06:42
@wyaeld agree on the point that the decision which Auth* system could be left to the developer. On the other, most people use Devise (even though I am not the biggest fan). Maybe we could talk about a plugin for auth or such ...

**Comment by GBH** [comment] 2015-04-01 14:56
`comfy-device` gem would be a nice option for those who want to have auth/users baked in. Anybody want to author that?

**Comment by andywenk** [comment] 2015-04-01 15:55
great idea @GBH . Unfortunately I am out because we already put a lot of effort into cms-fortress and I can't find spare time ... but I am happy seeing this in Comfy and am willing to help ripping it out of cms-fortress later

**Comment by GBH** [comment] 2015-04-19 19:22
Gonna close this one. But I still like an idea of `comfy-device`

**Closed by GBH** 2015-04-19 19:22 UTC
