### ISSUE TITLE
Tags are not available inside of CSS

### ISSUE THREAD

**Issue by mguterl** [comfy/comfortable-mexican-sofa#629] opened 2015-04-10 18:22 UTC
It would be nice to be able to use CMS or ERB tags inside of CSS files so that images can be referenced by name for background images.

For example:

To use an image stored in the CMS in a page or snippet:

``` html
<img src="{{ cms:file:icon-pub.png }}" alt="">
```

To use an image stored in the CMS in CSS:

```
.link-arrow {
  content: url("/system/comfy/cms/files/files/000/000/045/original/link-arrow.png");
}
```

We use CMS fixtures to export sites and re-import them and the ids referenced in the CSS change.

**Comment by GBH** [comment] 2015-04-19 19:10
Interesting. It's an idea. Should be pretty easy to run it through tag expander.

**Comment by schneikai** [comment] 2015-05-02 11:04
I posted this on Google Groups once https://groups.google.com/d/msg/comfortable-mexican-sofa/IFCN9KjHd9I/TmqtnlErvw8J :)

**Comment by GBH** [comment] 2017-11-19 21:19
Closing this as it's not a bug. PR is welcome.

**Closed by GBH** 2017-11-19 21:19 UTC
Labels: feature
