### ISSUE TITLE
Does not use @cms_page.layout when @cms_page is set

### ISSUE THREAD

**Issue by espen** [comfy/comfortable-mexican-sofa#520] opened 2014-09-10 08:02 UTC
I'll put up a test later but basically I have done this:

```
before_action :load_page

def load_page
    @cms_page = @cms_site.pages.find_by_slug!('mypage')
    @cms_layout = @cms_page.layout
end
```

renders with standard layout, not the layout specified in 'mypage'.

I have to explicitly specify it in each action:

```
    render :cms_layout => @cms_page.layout.identifier
```

**Comment by espen** [comment] 2015-01-23 20:08
I'm able to reproduce this. It occurs when setting cms site/page/layout manually in non-sofa routes. Then the layout is not disaplyed (a page with slug 'test' has been created with a specified layout). The contents of (yes/no.html.erb) is shown.

I can publish a git repo tomorrow if required.

Not sure if this is a bug or out of scope as it is doing custom routes though.

```ruby
get '/bug' => 'bugs#yes'
get '/nobug' => 'bugs#no'

class BugsController < ApplicationController

  before_action :load_cms_context

  def yes
  end

  def no
    render :cms_layout => @cms_page.layout.identifier
  end

  private

  def load_cms_context
    @cms_site = Comfy::Cms::Site.first
    @cms_page = @cms_site.pages.find_by_slug!( 'test' )
    @cms_layout = @cms_page.layout
  end

end
```

**Comment by GBH** [comment] 2015-01-23 20:57
Yes, please make a repo. I'll take a look.
You're kinda manually messing with cms variables, so maybe something unexpected is happening. I need to understand what the problem is first.

**Comment by espen** [comment] 2015-02-09 22:39
https://github.com/espen/sofa_layout_bug

**Comment by GBH** [comment] 2017-11-19 21:28
Closing as it's very old. But my guess that `render cms_layout: 'some-layout'` is not used properly. It really needs to have `cms_fragments` values sent to it. It won't use `@cms_page` at all.

**Closed by GBH** 2017-11-19 21:28 UTC
